### PR TITLE
Dashboard widget

### LINKED ISSUE #15: dashboard widget: 2 issues with the link to settings page
1. the URL is incorrect in multiste
2. there should be a `current_user_can()` check to decide whether to show the link, because not everyone seeing the widget will have the cap to edit the setting.

PR coming shortly.

### PR DESCRIPTION
**Pull request by pbiron**
ensure the link to the settings page is correct in multisite and check that current user has the correct cap to change the settings before showing the link.

Fixes #15

### CODE REVIEW

File: src/WPBT/WPBT_Beta_RC.php [hunk 1]
```diff
@@ -411,18 +411,25 @@ public function add_dashboard_widget() {
...
+		/* translators: %1: link to closed trac tickets on current milestone */
+		printf( wp_kses_post( '<p>' . __( 'Here are the <a href="%s">commits for the milestone</a>.', 'wordpress-beta-tester' ) . '</p>' ), esc_url_raw( "https://core.trac.wordpress.org/query?status=closed&milestone=$milestone" ) );
 
-		/* translators: %s: WP Beta Tester settings URL */
-		printf( wp_kses_post( '<p>' . __( 'Head over to your <a href="%s">WordPress Beta Tester Settings</a> and make sure the <strong>beta/RC</strong> stream is selected.', 'wordpress-beta-tester' ) . '</p>' ), esc_url_raw( $wpbt_settings_page ) );
+		// @todo make sure these capabilities stay in sync with what is used for the
+		//       settings page in WPBP_Settings::add_plugin_menu()
+		$capability = is_multisite() ? 'manage_network' : 'manage_options';
+		if ( current_user_can( $capability ) ) {
+			$parent             = is_multisite() ? 'settings.php' : 'tools.php';
```
Comment (afragen) [inline src/WPBT/WPBT_Beta_RC.php]: Probably `$page` would be a better variable name here.
```suggestion
			$page             = is_multisite() ? 'settings.php' : 'tools.php';
```

File: src/WPBT/WPBT_Beta_RC.php [hunk 2]
```diff
@@ -411,18 +411,25 @@ public function add_dashboard_widget() {
...
 
 		/* translators: %s: WordPress version */
 		printf( wp_kses_post( __( 'Please help test <strong>WordPress %s</strong>.', 'wordpress-beta-tester' ) ), esc_attr( $milestone ) );
 
 		echo wp_kses_post( $this->parse_development_feed( $milestone ) );
 
-		/* translators: %1: link to closed and reopened trac tickets on current milestone */
-		printf( wp_kses_post( '<p>' . __( 'Here are the <a href="%s">commits for the milestone</a>.', 'wordpress-beta-tester' ) . '</p>' ), esc_url_raw( "https://core.trac.wordpress.org/query?status=closed&status=reopened&milestone=$milestone" ) );
+		/* translators: %1: link to closed trac tickets on current milestone */
+		printf( wp_kses_post( '<p>' . __( 'Here are the <a href="%s">commits for the milestone</a>.', 'wordpress-beta-tester' ) . '</p>' ), esc_url_raw( "https://core.trac.wordpress.org/query?status=closed&milestone=$milestone" ) );
```
Comment (afragen) [inline src/WPBT/WPBT_Beta_RC.php]: I think I changed this before you made your commit.
```suggestion
		printf( wp_kses_post( '<p>' . __( 'Here are the <a href="%s">commits for the milestone</a>.', 'wordpress-beta-tester' ) . '</p>' ), esc_url_raw( "https://core.trac.wordpress.org/query?status=closed&status=reopened&milestone=$milestone" ) );
```

File: src/WPBT/WPBT_Beta_RC.php [hunk 3]
```diff
@@ -411,18 +411,25 @@ public function add_dashboard_widget() {
...
 		$milestone          = array_shift( $next_version );
-		$wpbt_settings_page = add_query_arg( 'page', 'wp_beta_tester', admin_url( 'tools.php' ) );
 
 		/* translators: %s: WordPress version */
 		printf( wp_kses_post( __( 'Please help test <strong>WordPress %s</strong>.', 'wordpress-beta-tester' ) ), esc_attr( $milestone ) );
 
 		echo wp_kses_post( $this->parse_development_feed( $milestone ) );
 
-		/* translators: %1: link to closed and reopened trac tickets on current milestone */
+		/* translators: %1: link to closed trac tickets on current milestone */
```
Comment (afragen) [inline src/WPBT/WPBT_Beta_RC.php]:
```suggestion
		/* translators: %1: link to closed and reopened trac tickets on current milestone */
```
